### PR TITLE
add VS Code and JetBrains IDE support

### PR DESCRIPTION
**Pull request by break-stuff**
This is a simple demonstration of how to add IDE support for DCEs. 

This PR includes the [CEM/Analyzer](https://custom-elements-manifest.open-wc.org/analyzer/getting-started/) as well as plugins to generate the needed files [VS Code](https://www.npmjs.com/package/custom-element-vs-code-integration) and [JetBrains IDE](https://www.npmjs.com/package/custom-element-jet-brains-integration) support.

The component definitions are in the `components.js` file. these are for documentation purposes only and shouldn't be used in production (also, they are necessary since you are using DCEs).

To generate the necessary config files for the editors, run `npm run analyze`. This will generate the `vscode.html-custom-data.json` and `web-types.json`.

### CODE REVIEW

**Comment by sashafirsov** [comment]
The DCE source project uses static `web-types.json` , added in `0.0.17`. The custom elements are not part of delivery, hence there is no need it on this project. Instead, they would be needed in [custom-element-bootstrap](https://github.com/EPA-WG/custom-element-bootstrap/tree/main).  Moving the code for IDE support there.

**Comment by break-stuff** [comment]
@sashafirsov Would you like me to create a PR for this there?

**Comment by sashafirsov** [comment]
@break-stuff , thanks for offer. The code which generates those files reside in https://github.com/EPA-WG/dce-parser/ and applied to this project. As of now they are up to date and no need for PR.

**Comment by sashafirsov** [comment]
The intermediate VSCode and IntelliJ config files are code generated by test proj and added to the main branch. Closing this PR as outdated.

**Pull request closed without merging**
